/**
 * Section Navigation items
 */
export const PERMISSION_ADMIN_USERS_LIST = 'manageUserRead'
export const PERMISSION_ADMIN_TARIFF_UPDATE = 'manageTariffUpdate'
export const PERMISSION_ADMIN_ROLES_LIST = 'manageRoleRead'
export const PERMISSION_MANAGE_PERMISSION_READ = 'managePermissionRead'
export const PERMISSION_ADMIN_COMPANY_LIST = 'manageCompanyRead'
export const PERMISSION_MY_COMPANY = 'clientCompanyRead'
export const PERMISSION_CLIENT_APPLICATION_LIST = 'clientApplicationRead'
export const PERMISSION_CLIENT_STATISTIC_LIST = 'clientApplicationStatisticRead'
export const PERMISSION_CLIENT_DOMAINS_LIST = 'manageDomainRead'
export const PERMISSION_ADMIN_PUSH_TEMPLATES_LIST = 'managePushTemplateRead'
export const PERMISSION_ADMIN_SINGLE_PUSH_NOTIFICATIONS_LIST = 'manageSinglePushNotificationRead'
export const PERMISSION_CLIENT_TELEGRAM_BOT_EDIT = 'clientNotificationTelegramBotUpdate'
export const PERMISSION_ADMIN_TG_BOT_LIST = 'manageTelegraphBotRead'
export const PERMISSION_ADMIN_SYSTEM_NOTIFICATIONS = 'manageNotificationTemplateRead'
export const PERMISSION_CLIENT_SYSTEM_NOTIFICATIONS = 'clientNotificationRead'

/**
 * Section manage
 */
export const PERMISSION_ADMIN_COMPANY_UPDATE = 'manageCompanyUpdate'
export const PERMISSION_ADMIN_COMPANY_MANUAL_BALANCE_DEPOSIT = 'manageCompanyManualBalanceDeposit'
export const PERMISSION_ADMIN_COMPANY_BALANCE_TRANSACTIONS_READ =
  'manageCompanyBalanceTransactionsRead'
export const PERMISSION_ADMIN_USERS_UPDATE = 'manageUserUpdate'
export const PERMISSION_ADMIN_LOGIN_AS_USER = 'manageUserLoginAsUser'
export const PERMISSION_CLIENT_APPLICATION_EDIT = 'clientApplicationSave'
export const PERMISSION_CLIENT_APPLICATION_DELETE = 'clientApplicationDelete'

export const PERMISSION_CLIENT_COMPANY_EDIT = 'clientCompanyUpdate'
export const PERMISSION_CLIENT_COMPANY_INVITE = 'clientCompanyInvite'
export const PERMISSION_CLIENT_TEAMS_LIST = 'clientTeamRead'
export const PERMISSION_CLIENT_USERS_LIST = 'clientUserRead'
export const PERMISSION_CLIENT_TARIFF_READ = 'clientTariffRead'
export const PERMISSION_ADMIN_TG_BOT_ACTIVE = 'manageTelegramBotUpdate'
export const PERMISSION_ADMIN_PUSH_TEMPLATES_STORE = 'managePushTemplateCreate'
export const PERMISSION_ADMIN_PUSH_TEMPLATES_UPDATE = 'managePushTemplateUpdate'
export const PERMISSION_ADMIN_REGULAR_PUSH_NOTIFICATIONS_LIST = 'manageRegularPushNotificationRead'
export const PERMISSION_MANAGE_PUSH_NOTIFICATION_READ = 'managePushNotificationRead'
export const PERMISSION_ADMIN_PUSH_NOTIFICATIONS_STORE = 'managePushNotificationCreate'
export const PERMISSION_ADMIN_PUSH_NOTIFICATIONS_UPDATE = 'managePushNotificationUpdate'
export const PERMISSION_ADMIN_PUSH_NOTIFICATIONS_DELETE = 'managePushNotificationDelete'
export const PERMISSION_ADMIN_PUSH_NOTIFICATIONS_COPY = 'managePushNotificationClone'
export const PERMISSION_ADMIN_PUSH_NOTIFICATIONS_STATISTIC = 'managePushNotificationStatisticRead'

export const PERMISSION_ADMIN_ROLE_UPDATE = 'manageRoleUpdate'
export const PERMISSION_ADMIN_ROLE_CREATE = 'manageRoleCreate'
export const PERMISSION_ADMIN_ROLE_DESTROY = 'manageRoleDelete'
export const PERMISSION_CLIENT_DOMAINS_CREATE = 'manageDomainCreate'
export const PERMISSION_CLIENT_DOMAINS_UPDATE = 'manageDomainUpdate'
export const PERMISSION_CLIENT_APPLICATION_UPDATE_OWNER = 'clientApplicationOwnerUpdate'
export const PERMISSION_MANAGE_NOTIFICATION_TEMPLATE_CREATE = 'manageNotificationTemplateCreate'
export const PERMISSION_MANAGE_NOTIFICATION_TEMPLATE_SEND_MESSAGE =
  'manageNotificationTemplateSendMessage'
export const PERMISSION_MANAGE_NOTIFICATION_TEMPLATE_DELETE = 'manageNotificationTemplateDelete'
export const PERMISSION_MANAGE_NOTIFICATION_TEMPLATE_UPDATE = 'manageNotificationTemplateUpdate'
export const PERMISSION_CLIENT_APPLICATION_CLONE = 'clientApplicationClone'
export const PERMISSION_CLIENT_NOTIFICATION_ACTIVATE = 'clientNotificationActivate'
export const PERMISSION_CLIENT_TEAM_CREATE = 'clientTeamCreate'
export const PERMISSION_CLIENT_TEAM_UPDATE = 'clientTeamUpdate'
export const PERMISSION_CLIENT_TEAM_INVITE = 'clientTeamInvite'
export const PERMISSION_CLIENT_TEAM_DELETE = 'clientTeamDelete'
export const PERMISSION_CLIENT_USER_DEACTIVATE = 'clientUserDeactivate'
export const PERMISSION_MANAGE_APPLICATION_READ = 'manageApplicationRead'
export const PERMISSION_MANAGE_APPLICATION_SAVE = 'manageApplicationSave'
export const PERMISSION_MANAGE_APPLICATION_DELETE = 'manageApplicationDelete'
export const PERMISSION_MANAGE_APPLICATION_CLONE = 'manageApplicationClone'
